name: Update YouBike Data

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  # 允許在 GitHub 頁面手動點擊按鈕執行
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    # 🌟 關鍵：明確授予 GITHUB_TOKEN 寫入權限 🌟
    permissions:
      contents: write

    steps:
      - name: Check out repository
        # 使用專門 Action 處理 checkout
        uses: actions/checkout@v4
        with:
          # 🌟 使用您的 PAT，確保高權限驗證 (解決 403) 🌟
          token: ${{ secrets.GH_PAT }}
          # 取得完整的 Git 歷史，這是 Auto-Commit Action 處理衝突所需要的
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch new data
        env:
          TDX_CLIENT_ID: ${{ secrets.TDX_CLIENT_ID }}
          TDX_CLIENT_SECRET: ${{ secrets.TDX_CLIENT_SECRET }}
        run: python fetch_data.py --source tdx

      # 🌟 核心解決方案：自動處理 Commit, Pull/Rebase, 和 Push 🌟
      - name: Commit and Push Changes Automatically
        # 使用專門 Action，它會自動處理 'fetch first' 錯誤
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'src/stations.json'
          commit_message: 'Automated data update'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          # 這個 Action 會在 push 前自動執行 git pull --rebase 來解決您現在的錯誤。
